export const exercises = [
                           {
                             "e_id": 0,
                             "name": "Bench Press",
                             "type": "Strength Training",
                             "description": "A reclined barbell exercise",
                             "muscle_group": "chest shoulders arms",
                             "id": "5634601401712640",
                             "user": "auth0|6486842ce70d24cefd414c3b",
                           },
                           {
                            "e_id" : 1,
                             "name": "Push Up",
                             "type": "Strength Training",
                             "description": "A bodyweight exercise performed on the floor",
                             "muscle_group": "chest shoulders triceps ",
                             "id": "209450140583941",
                             "user": "auth0|6486842ce70d24cefd414c3b",
                           },
                           {
                             "e_id": 2,
                             "name": "Triceps Pushdown",
                             "type": "Strength Training",
                             "description": "A standing cable exercise",
                             "muscle_group": "chest shoulders triceps",
                             "id": "884702330205829",
                             "user": "",
                           },
                           {
                              "e_id": 3,
                              "name": "Lateral Raises",
                              "type": "Strength Training",
                              "description": "A standing dumbbell exercise",
                              "muscle_group": "chest shoulders triceps",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 4,
                              "name": "Barbell Row",
                              "type": "Strength Training",
                              "description": "A bent over barbell exercise",
                              "muscle_group": "back biceps",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 5,
                              "name": "Dumbbell Curls",
                              "type": "Strength Training",
                              "description": "A standing dumbbell exercise",
                              "muscle_group": "back biceps",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 6,
                              "name": "Lat Pulldown",
                              "type": "Strength Training",
                              "description": "A seated cable exercise",
                              "muscle_group": "back biceps",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 7,
                              "name": "Preacher Curls",
                              "type": "Strength Training",
                              "description": "A seated or standing barbell or dumbbell exercise",
                              "muscle_group": "back biceps",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 8,
                              "name": "Barbell Squat",
                              "type": "Strength Training",
                              "description": "A standing/squatting barbell exercise",
                              "muscle_group": "quads glutes",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 9,
                              "name": "Walking Lunges",
                              "type": "Strength Training",
                              "description": "A walking lunge dumbbell exercise",
                              "muscle_group": "quads glutes",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 10,
                              "name": "Romanian Deadlifts",
                              "type": "Strength Training",
                              "description": "A standing to bent over barbell or dumbbell exercise",
                              "muscle_group": "hamstrings glutes",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 11,
                              "name": "Leg Extensions",
                              "type": "Strength Training",
                              "description": "A seated machine exercise",
                              "muscle_group": "quads",
                              "id": "884702330205829",
                              "user": "",
                           }

                         ]

