export const exercises = [
                           {
                             "e_id": 0,
                             "name": "Bench Press",
                             "category": "Strength",
                             "type": "Strength",
                             "description": "Lie with your back on a weight bench and then lower a barbell to your chest and press it back up",
                             "muscle_group": "Chest",
                             "duration": "60",
                             "equipment": "Bench, barbell",
                             "id": "5634601401712640",
                             "user": "auth0|6486842ce70d24cefd414c3b",
                           },
                           {
                            "e_id" : 1,
                             "name": "Push-ups",
                             "category": "Strength",
                             "type": "Strength",
                             "description": "From the plank position, lower yourself to the floor and then push up",
                             "muscle_group": "Chest",
                             "duration": "60",
                             "equipment": "None",
                             "id": "209450140583941",
                             "user": "auth0|6486842ce70d24cefd414c3b",
                           },
                           {
                             "e_id": 2,
                             "name": "Tricep pushdowns",
                             "category": "Strength",
                             "type": "Strength",
                             "description": "Grab the cable and pull it down until your arms are straight and gradually bend your arms to raise the cable",
                             "muscle_group": "Triceps",
                             "duration": "60",
                             "equipment": "Cable machine",
                             "id": "884702330205829",
                             "user": "",
                           },
                           {
                              "e_id": 3,
                              "name": "Lateral Raises",
                              "category": "Strength",
                              "type": "Strength",
                              "description": "Stand with your arms at your sides with a dumbbell in each hand, then raise your arms out to the sides, parallel with the floor",
                              "muscle_group": "Shoulders",
                              "duration": "60",
                              "equipment": "Dumbbells",
                              "id": "884702330205829",
                              "user": "",
                           },
                           // {
                           //    "e_id": 4,
                           //    "name": "Dumbbell rows",
                           //    "category": "Strength",
                           //    "type": "Pull",
                           //    "description": "Lean over on bench with one arm, holding dumbell in your other straightened arm, and slowly raise your arm up until your elbow is behind you and lower it back down",
                           //    "muscle_group": "Back",
                           //    "duration": "60",
                           //    "equipment": "Dumbbells",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           // {
                           //    "e_id": 5,
                           //    "name": "Preacher curls",
                           //    "category": "Strength",
                           //    "type": "Pull",
                           //    "description": "Grab the bar in front of you with your elbows resting on the bench and then perform a curl keeping your elbows in place",
                           //    "muscle_group": "Biceps",
                           //    "duration": "60",
                           //    "equipment":"Dumbbells",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           // {
                           //    "e_id": 6,
                           //    "name": "Lat pulldowns",
                           //    "category": "Strength",
                           //    "type": "Pull",
                           //    "description": "Grab the bar on the machine with your arms outstretched overhead, with palms facing away from you, and gradually lower the bar down to your chest and release",
                           //    "muscle_group": "Back",
                           //    "duration": "60",
                           //    "equipment":"Pulldown machine",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           // {
                           //    "e_id": 7,
                           //    "name": "Bicep curls",
                           //    "category": "Strength",
                           //    "type": "Pull",
                           //    "description": "Stand up straight with a dumbbell in each hand with your arms straightened to your sides and slowly lift each arm up to bring the weight to your shoulder without moving your arm above the elbow and lower down",
                           //    "muscle_group": "Biceps",
                           //    "duration": "60",
                           //    "equipment": "Dumbbells",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           // {
                           //    "e_id": 8,
                           //    "name": "Barbell Squat",
                           //    "category": "Strength",
                           //    "type": "Legs",
                           //    "description": "With a barbell across your shoulders, lower down into a squat and then press back up",
                           //    "muscle_group": "Quads",
                           //    "duration": "60",
                           //    "equipment": "Barbell",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           // {
                           //    "e_id": 9,
                           //    "name": "Calf raises",
                           //    "category": "Strength",
                           //    "type": "Legs",
                           //    "description": "Standing with dumbbells by your side, stand up on your tiptoes and then lower down",
                           //    "muscle_group": "Calves",
                           //    "duration": "60",
                           //    "equipment": "Dumbbells",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           // {
                           //    "e_id": 10,
                           //    "name": "Step Ups",
                           //    "category": "Strength",
                           //    "type": "Legs",
                           //    "description": "Standing with dumbbells at your sides, step up onto a step and then lower back down.",
                           //    "muscle_group": "Glutes",
                           //    "duration": "60",
                           //    "euipment": "Box, Dumbbells",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           // {
                           //    "e_id": 11,
                           //    "name": "Good mornings",
                           //    "category": "Strength",
                           //    "type": "Legs",
                           //    "description": "With a barbell across your shoulders and your back leaned slightly over (but straight), stand up tall and then lower back down.",
                           //    "muscle_group": "Hamstrings",
                           //    "duration": "60",
                           //    "equipment": "Barbell",
                           //    "id": "884702330205829",
                           //    "user": "",
                           // },
                           {
                              "e_id": 4,
                              "name": "Cat-Cow",
                              "category": "Timed",
                              "type": "Flexibility",
                              "description": "On all fours, arch your back on the inhale, round your back on the exale. Repeat.",
                              "duration": "10",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 5,
                              "name": "Run",
                              "type": "Cardio",
                              "category": "Timed",
                              "description": "Slightly lean forward from your waist while engaging your core. Lift your chest, soften your shoulders, and draw them away from your ears",
                              "duration": "900",
                              "id": "884702330205829",
                              "user": "",
                           },
                           {
                              "e_id": 6,
                              "name": "Hamstring Stretch",
                              "type": "Flexibility",
                              "category": "Timed",
                              "description": "Sitting on the floor, bend one leg so that your foot is against the inside of the opposite thigh and stretch the other out in front of you. Stretch towards your outstretched leg with both hands. Repeat on the other side.",
                              "duration": "10",
                              "id": "884702330205829",
                              "user": "",
                           },

                         ]

